apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
  labels:
    app: php-app
spec:
  replicas: 10
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php-app
        image: 479035685370.dkr.ecr.ca-central-1.amazonaws.com/vikasgirigoswami1983:latest
        ports:
        - containerPort: 80
